#!/usr/bin/env python3
"""
save_artifact.py — PRD Artifact Save Hook

Saves a generated PRD to outputs/generated_prds/ with a timestamped filename.
Runs as a PostToolUse hook after successful PRD validation.

Exit codes:
  0 — artifact saved successfully
  1 — save failed (Claude will see the error)

Hook input (stdin): JSON with tool use details from Claude Code
"""

import json
import sys
import os
import re
import shutil
from datetime import datetime
from pathlib import Path


def extract_product_name(content: str) -> str:
    """
    Extract product name from PRD content for use in filename.
    Falls back to 'product' if not found.
    """
    # Try to find "**Product:** [Name]" or "# [Name] PRD" patterns
    patterns = [
        r"\*\*Product:\*\*\s*([^\n]+)",
        r"^#\s+([^\n]+)\s+PRD",
        r"^#\s+([^\n]+)\s+Product Requirements",
    ]
    for pattern in patterns:
        match = re.search(pattern, content, re.IGNORECASE | re.MULTILINE)
        if match:
            name = match.group(1).strip()
            # Clean to filesystem-safe slug
            slug = re.sub(r"[^a-zA-Z0-9\s-]", "", name)
            slug = re.sub(r"\s+", "_", slug).lower()
            return slug[:40]  # cap length

    return "product"


def get_output_dir() -> Path:
    """
    Determine the output directory.
    Uses PROJECT_ROOT env var if set, otherwise searches for outputs/ relative to cwd.
    """
    project_root = os.environ.get("PROJECT_ROOT")
    if project_root:
        return Path(project_root) / "outputs" / "generated_prds"

    # Walk up from cwd to find outputs/generated_prds
    current = Path.cwd()
    for _ in range(5):
        candidate = current / "outputs" / "generated_prds"
        if candidate.exists():
            return candidate
        current = current.parent

    # Default: create relative to cwd
    return Path.cwd() / "outputs" / "generated_prds"


def main():
    # Read hook input from stdin
    try:
        hook_input = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        sys.exit(0)

    tool_name = hook_input.get("tool_name", "")
    tool_input = hook_input.get("tool_input", {})
    tool_result = hook_input.get("tool_result", {})

    # Only act on successful Write tool calls to PRD output paths
    if tool_name != "Write":
        sys.exit(0)

    file_path = tool_input.get("file_path", "")
    if "generated_prds" not in file_path and "outputs" not in file_path:
        sys.exit(0)

    # Check if the write succeeded
    if tool_result.get("error"):
        sys.exit(0)

    content = tool_input.get("content", "")

    # Generate timestamped filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    product_slug = extract_product_name(content)
    filename = f"prd_{product_slug}_{timestamp}.md"

    # Ensure output directory exists
    output_dir = get_output_dir()
    output_dir.mkdir(parents=True, exist_ok=True)

    artifact_path = output_dir / filename

    # Save the artifact
    try:
        with open(artifact_path, "w", encoding="utf-8") as f:
            f.write(content)
            # Add metadata footer
            f.write(f"\n\n---\n")
            f.write(f"*Generated by claude_code_prd_generator*  \n")
            f.write(f"*Saved: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*  \n")
            f.write(f"*File: {filename}*\n")

    except OSError as e:
        print(f"ARTIFACT SAVE ERROR: Failed to write {artifact_path}: {e}", file=sys.stderr)
        sys.exit(1)

    # Also copy if the original path differs (Claude may have written to a temp location)
    original_path = Path(file_path)
    if original_path != artifact_path and original_path.exists():
        try:
            shutil.copy2(original_path, artifact_path)
        except OSError:
            pass  # Non-critical if copy fails — we already wrote the content

    print(f"PRD artifact saved: {artifact_path}")
    sys.exit(0)


if __name__ == "__main__":
    main()
